### ISSUE TITLE
Something is very broken in mill-bsp

### ISSUE THREAD

**Issue by arturaz** [com-lihaoyi/mill#5715]
The developer experience in large-ish project is practically unusable.

It was similar in Mill 0.12.x, thus I used bloop, but since Mill 1.0.x Bloop is gone :|

https://youtu.be/ArWv5fA9TYA

This isn't actionable for now, but I'll keep seeing if I hit issues and add recordings of those to this issue.

**Comment by arturaz** [comment]
I see these exceptions, which IMHO are spurious, as the code is still compiling when this occurs. But this is probably a metals bug:
```
2025.08.18 20:18:48 INFO  compiling target appclientprelude
2025.08.18 20:18:49 INFO  BSP server: [54-scalaMainClasses-2050] [info] compiling 8 Scala sources to /home/arturas/work/rapix/out/appClientPrelude/compile.dest/classes ...
2025.08.18 20:18:51 INFO  BSP server: [54-scalaMainClasses-2050] [info] done compiling
2025.08.18 20:18:51 INFO  time: compiled appClientPrelude in 1.75s
2025.08.18 20:18:51 INFO  compiling target appclient
2025.08.18 20:18:51 INFO  BSP server: [54-scalaMainClasses-2057] [info] compiling 62 Scala sources to /home/arturas/work/rapix/out/appClient/compile.dest/classes ...
2025.08.18 20:18:52 INFO  Scala test classes not supported by server
java.util.concurrent.TimeoutException: Future timed out after [1 minute]
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.Await$.result(package.scala:124)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionScalaFuture.$anonfun$withTimeout$1(MetalsEnrichments.scala:296)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1583)

2025.08.18 20:18:52 INFO  Scala main classes not supported by server
java.util.concurrent.TimeoutException: Future timed out after [1 minute]
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.Await$.result(package.scala:124)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionScalaFuture.$anonfun$withTimeout$1(MetalsEnrichments.scala:296)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1583)

2025.08.18 20:19:02 INFO  BSP server: [54-scalaMainClasses-2043] [info] done compiling
2025.08.18 20:19:02 INFO  time: compiled appServer in 13s
2025.08.18 20:19:02 INFO  compiling target appserver.tests
```

Or, perhaps, responses to these queries shouldn't be blocked by compilation, if that's possible.

**Comment by arturaz** [comment]
I noticed that it's using Zinc worker, so the whole experience might be related to https://github.com/com-lihaoyi/mill/pull/5713 / https://github.com/com-lihaoyi/mill/pull/5710

**Comment by alexarchambault** [comment]
mill-bsp is the main way I develop on Mill (albeit via a custom LSP server of mine rather than Metals), there were many issues ~1 year ago, but it should (and does for me) have gotten a lot better since. I've been reverting https://github.com/com-lihaoyi/mill/commit/d6c5336d699598a98a9b8b060705d21759620ff0 locally, mill-bsp works fine this way.

**Comment by arturaz** [comment]
> albeit via a custom LSP server of mine rather than Metals

Can you elaborate?

**Comment by lihaoyi** [comment]
BSP not being blocked by terminal compilation requests should be fixed by https://github.com/com-lihaoyi/mill/pull/5689

**Comment by arturaz** [comment]
> BSP not being blocked by terminal compilation requests should be fixed by [#5689](https://github.com/com-lihaoyi/mill/pull/5689)

Was this a reference to this?
```
2025.08.18 20:18:52 INFO  Scala test classes not supported by server
java.util.concurrent.TimeoutException: Future timed out after [1 minute]
````

**Comment by alexarchambault** [comment]
Now that I think about it, it feels compiling from BSP has become really slow. I didn't develop much between ~mid-July and mid-August. It seems it's been like this since mid-August for me. IIRC, it wasn't as bad back in July. https://github.com/com-lihaoyi/mill/pull/5689 didn't fix that (while it did for the `BspServerTests`).

**Comment by alexarchambault** [comment]
> Now that I think about it, it feels compiling from BSP has become really slow. I didn't develop much between ~mid-July and mid-August. It seems it's been like this since mid-August for me. IIRC, it wasn't as bad back in July. [#5689](https://github.com/com-lihaoyi/mill/pull/5689) didn't fix that (while it did for the `BspServerTests`).

It might just be that we (legitimately) compile more things since https://github.com/com-lihaoyi/mill/pull/5692, hence my impression that BSP compilation takes longer...

**Comment by nguyenyou** [comment]
Could this be addressed before cutting the `1.0.4` release? I just encountered a stack overflow when running `./mill __.compiledClassesAndSemanticDbFiles` on our largest codebase using version `1.0.3-57-9d2561`.

**Comment by lihaoyi** [comment]
@nguyenyou please open a ticket with a self-contained reproduction or a bisect pinpointing the offending commit in the Mill repository. Until then there is nothing we can do to help you

**Comment by nguyenyou** [comment]
@lihaoyi  I totally understand your point. In this case, the stack overflow only occurred when I tried compiling the semanticdb for our entire codebase — mainly to check whether the recent BSP/semanticdb changes improved things. Normally I work with IntelliJ on this large codebase, so I wouldn’t normally hit this path. I only ran that command for Metals while using Cursor.

Given that, I think I’ll hold off for now and wait a few days or weeks before digging deeper and trying to provide a reproduction or bisect. Thanks for the quick response!

**Comment by lihaoyi** [comment]
Closing this for now
